apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: hanzo-bridge
  namespace: hanzo-bridge
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`bridge.hanzo.network`)
      kind: Rule
      services:
        - name: hanzo-bridge
          port: 80
  tls:
    secretName: hanzo-bridge-tls
